springfox:
  documentation:
    open-api.v3.path: /api-docs
server:
  port: 8080
  servlet:
    contextPath: /
elasticsearch:
   url: microk8s-vm.mshome.net:32330 
spring:
  jackson:
    date-format: org.eclipse.basyx.aas.registry.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  kafka:
    bootstrap-servers: microk8s-vm.mshome.net:32100
  cloud:
    stream:
      bindings:
        default:
           key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
           value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        aasRegistryBinding:
          destination: aas-registry
          content-type: application/json
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 1

            
            