springfox:
  documentation:
    open-api.v3.path: /api-docs
server:
  port: 8080
  servlet:
    contextPath: /
spring:
  jackson:
    date-format: org.eclipse.basyx.aas.registry.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      bindings:
        aasRegistryBinding:
          destination: aas-registry
          content-type: application/json
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 1
