---
springfox:
  documentation:
    open-api.v3.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,beans"
logging:
  level:
    root: INFO
server:
  port: 8080
  servlet:
    contextPath: /
cors: 
  mappings: []    
elasticsearch:
   url: ${ELASTICSEARCH_HOST_URL}
spring:
  jackson:
    date-format: org.eclipse.basyx.aas.registry.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  cloud:
    stream:
      bindings:
        default:
           key-desewrializer: org.apache.kafka.common.serialization.StringDeserializer
           value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        aasRegistryBinding:
          destination: aas-registry
          content-type: application/json
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 1
            