version: '3.6'

networks:
  basyx:
    internal: false

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  elasticsearch-data:
    driver: local
  aas-config:
services:  
  portainer:
    image: portainer/portainer:latest
    container_name: basyx-portainer
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basyx
      
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - basyx
      
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    hostname: kafka
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${HOSTNAME}:9092,
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - basyx

  aas-server:
    image: docker.io/dfkibasys/aas-server:0.3.0-SNAPSHOT
    container_name: aasServer
    ports:
      - 8090:8080
    networks:
      - basyx
 
 
  # aas-registry:
  #   image: geso02/aasregistry-dotaas-part2:0.1.0-kafka-es
  #   container_name: aasRegistry
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #     - elasticsearch
  #   networks:
  #     - basyx

  akhq:
    image: tchiotludo/akhq:dev
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 8086:8080
    restart: always
    depends_on:
      - kafka
      - zookeeper
    networks:
      - basyx

  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data     
    environment:
      - discovery.type=single-node  
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - basyx
  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - basyx