---
cors:
  mappings:
    # If just the path is specified, defaults are used
    - path: /**
      # allowCredentials: false
      # allowedHeaders: []
      # allowedMethods: []
      # allowedOriginPatterns: []
      # allowedOrigins: []
      # exposedHeaders: []
      # maxAge: -1