---
openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Registry and Discovery and Search
  version: Final-Draft + Search
paths:
  /registry/shell-descriptors/search:
    post:
      operationId: SearchShellDescriptors
      tags:
        - Registry and Discovery Interface
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShellDescriptorSearchQuery'
        required: true
      responses:
        "200":
          description: Search response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShellDescriptorSearchResponse'   
components:
  schemas:
    Reference:
      discriminator:
        propertyName: _rType
    GlobalReference:
      properties:
        _rType: 
          type: string
          default: GlobalReference
    ModelReference:
      properties:
        _rType:
          type: string
          default: ModelReference
    ShellDescriptorSearchQuery:
      type: object
      properties:
        required:
          - path
          - value
        sorting: 
          type: Sorting
        path:
          type: string
        value:
          type: string
    Sorting:
      type: object
      required:
        - property
      properties:
        direction:
          $ref: '#/components/schemas/SortDirection'
        property:
          type: string
    SortDirection:
       type: string
       enum: [ "ASC", "DESC"]
    ShellDescriptorSearchResponse:
      type: object
      required:
        - hits
      properties:
        hits:
          type: array
          items: 
            $ref: '#/components/schemas/AssetAdministrationShellDescriptor'