---
openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Registry and Discovery and Search
  version: V1.0RC03 + Search
servers: []
paths:
  /shell-descriptors:
    get:
      tags:
         - Registry and Discovery Interface
    post:
      tags:
         - Registry and Discovery Interface
    delete:
      tags:
         - Registry and Discovery Interface
      summary: Deletes all Asset Administration Shell Descriptors
      operationId: DeleteAllShellDescriptors
      responses:
        '204':
          description: No content
      x-semanticIds:
      - https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptors/1/0/RC03
  /shell-descriptors/{aasIdentifier}:
    get:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
    put:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
          overlay:
             0:
                x-utf8-base64-url-encoded-as-string: true
    delete:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
  /shell-descriptors/{aasIdentifier}/submodel-descriptors:
    get:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true  
    post:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
  /shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier}:
    get:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
              1:
                 x-utf8-base64-url-encoded-as-string: true
    put:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
              1:
                 x-utf8-base64-url-encoded-as-string: true
    delete:
      tags:
         - Registry and Discovery Interface
      parameters:
        $LIST_PROCESS_INSTRUCTION$:
           overlay:
              0:
                 x-utf8-base64-url-encoded-as-string: true
              1:
                 x-utf8-base64-url-encoded-as-string: true
  # these both are not implemented for now so remove them using overlay
  /lookup/shells: {}
  /lookup/shells/{aasIdentifier}: {}
  /search:
    post:
      operationId: SearchShellDescriptors
      tags:
         - Registry and Discovery Interface 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShellDescriptorSearchRequest'
        required: true
      responses:
        '200':
          description: Search response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShellDescriptorSearchResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    ShellDescriptorSearchRequest:
      type: object
      properties:
        page:
          $ref: '#/components/schemas/Page'
        sortBy: 
          $ref: '#/components/schemas/Sorting'
        query:
          $ref: '#/components/schemas/ShellDescriptorQuery'
    ShellDescriptorQuery:      
      required:
        - queryType
        - path
        - value
      properties:
        path:
          type: string
        value:
          type: string
        queryType:
          type: string
          enum: ['match', 'regex']
    Page:
       type: object
       required:
          - index
          - size
       properties:
          index:
             type: integer
             minimum: 0
          size: 
             type: integer
             minimum: 1
             maximum: 10000 
    Sorting:
      type: object
      required:
        - path
      properties:
        direction:
          $ref: '#/components/schemas/SortDirection'
        path:
           type: array
           items:
              $ref: '#/components/schemas/SortingPath'
    SortingPath:
       type: string
       enum: 
          - idShort
          - identification
          - administration.revision
          - administration.version
    SortDirection:
       type: string
       enum: [ "ASC", "DESC"]
    ShellDescriptorSearchResponse:
      type: object
      required:
        - hits
        - total
      properties:
        total:
           type: integer
           format: int64
           minimum: 0
        hits:
          type: array
          items: 
            $ref: '#/components/schemas/AssetAdministrationShellDescriptor'