---
openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Registry and Discovery and Search
  version: Final-Draft + Search
paths:
  /registry/shell-descriptors/search:
    post:
      operationId: SearchShellDescriptors
      tags:
        - Registry and Discovery Interface
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShellDescriptorSearchQuery'
        required: true
      responses:
        "200":
          description: Search response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShellDescriptorSearchResponse'   
        "400":
           description: Invalid request
           content:
            application/json:
              schema: 
                $ref: '#/components/schemas/IllegalRequest'
components:
  schemas:
    IllegalRequest:
       type: string
    Reference:
      discriminator:
        propertyName: _rType
    GlobalReference:
      properties:
        _rType: 
          type: string
          default: GlobalReference
    ModelReference:
      properties:
        _rType:
          type: string
          default: ModelReference
    ShellDescriptorSearchQuery:
      type: object
      properties:
        page:
           $ref: '#/components/schemas/Page'
        sortBy: 
           $ref: '#/components/schemas/Sorting'
        match:
         $ref: '#/components/schemas/Match'
    Match:
       required:
          - path
          - value
       properties:
          path:
            type: string
          value:
            type: string
    Page:
       type: object
       required:
          - index
          - size
       properties:
          index:
             type: integer
             minimum: 0
          size: 
             type: integer
             minimum: 0
             maximum: 10000 
    Sorting:
      type: object
      required:
        - path
      properties:
        direction:
          $ref: '#/components/schemas/SortDirection'
        path:
           type: array
           items:
              $ref: '#/components/schemas/SortingPath'
    SortingPath:
       type: string
       enum: 
          - idShort
          - identification
          - administration.revision
          - administration.version
    SortDirection:
       type: string
       enum: [ "ASC", "DESC"]
    ShellDescriptorSearchResponse:
      type: object
      required:
        - hits
        - total
      properties:
        total:
           type: integer
           format: int64
           minimum: 0
        hits:
          type: array
          items: 
            $ref: '#/components/schemas/AssetAdministrationShellDescriptor'